# Generated by Django 4.2.1 on 2023-06-09 04:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='FoodSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sale_type', models.CharField(choices=[('L', 'Lunch'), ('D', 'Dinner')], default='L', max_length=1)),
                ('price', models.DecimalField(decimal_places=3, max_digits=5)),
                ('outgoing', models.IntegerField()),
                ('incoming', models.IntegerField()),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.counter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.item')),
            ],
            options={
                'ordering': ['-date', 'counter', 'sale_type', 'item'],
                'indexes': [models.Index(fields=['counter'], name='sales_foods_counter_46c9d9_idx'), models.Index(fields=['item'], name='sales_foods_item_id_f80c5d_idx'), models.Index(fields=['date', 'counter', 'item'], name='sales_foods_date_f3ccf5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='foodsale',
            constraint=models.UniqueConstraint(fields=('item', 'date', 'counter', 'sale_type'), name='unique_food_sale'),
        ),
    ]
